version: '3.8'

x-bases-app: &base
  restart: always
  networks:
    - main


services:
  backend:
    <<: *base
    image: backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend_data:/backend_data
    depends_on:
      - postgres
      - redis

  postgres:
    <<: *base
    image: docker.arvancloud.ir/postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tourism
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    <<: *base
    image: docker.arvancloud.ir/redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

networks:
  main:

volumes:
  postgres_data:
  redis_data: